/**
 * Blueprint académico exclusivo del área "Pediatría & Neonatología".
 * Estructura de dos bloques (Neonatología / Pediatría) con categorías y temas.
 * Solo estructura — no modifica ningún módulo previo.
 */

export interface BlueprintTopic {
  title: string;
  items?: string[];
}

export interface BlueprintCategory {
  key: string;
  title: string;
  topics: BlueprintTopic[];
}

export interface BlueprintBlock {
  key: "neonatologia" | "pediatria";
  title: string;
  tagline: string;
  accent: string;
  categories: BlueprintCategory[];
}

/** Formato estándar de cada enfermedad/tema clínico. */
export const TOPIC_STANDARD_FORMAT: string[] = [
  "Resumen ejecutivo (1 minuto)",
  "Conceptos clave",
  "Anatomía y fisiología relacionada",
  "Definición",
  "Epidemiología",
  "Etiología",
  "Factores de riesgo",
  "Fisiopatología ilustrada",
  "Manifestaciones clínicas",
  "Diagnóstico diferencial",
  "Algoritmo diagnóstico",
  "Laboratorio",
  "Imágenes",
  "Escalas",
  "Tratamiento basado en guías (MINSA, AAP, ESPGHAN, WHO)",
  "Seguimiento y pronóstico",
  "Complicaciones",
  "Errores frecuentes",
  "Perlas ENAM",
  "Perlas ESSALUD",
  "Perlas Residentado",
  "Caso clínico interactivo",
  "Flashcards",
  "Preguntas tipo examen",
  "Resumen de una página",
  "Mapa mental",
  "Infografía descargable",
  "Video corto",
  "Podcast",
  "Referencias bibliográficas",
  "Banco de preguntas",
];

export const NEONATOLOGIA: BlueprintBlock = {
  key: "neonatologia",
  title: "Neonatología",
  tagline: "Nivel Premium — del parto al alta neonatal.",
  accent: "oklch(0.68 0.13 260)",
  categories: [
    {
      key: "atencion-inmediata",
      title: "A. Atención inmediata",
      topics: [
        { title: "Atención en sala de partos" },
        { title: "Reanimación neonatal" },
        { title: "APGAR" },
        { title: "Silverman" },
        { title: "Clampaje" },
        { title: "Adaptación neonatal" },
        { title: "Termorregulación" },
        { title: "Atención inmediata MINSA" },
        { title: "Profilaxis" },
        { title: "Tamizajes" },
      ],
    },
    {
      key: "patologia-neonatal",
      title: "B. Patología neonatal",
      topics: [
        { title: "Prematuridad" },
        { title: "PEG" },
        { title: "GEG" },
        { title: "Macrosomía" },
        { title: "Restricción del crecimiento" },
        { title: "Hipoglicemia" },
        { title: "Hipocalcemia" },
        { title: "Hipotermia" },
        { title: "Policitemia" },
        { title: "Anemia" },
        { title: "Hemorragias" },
        { title: "Sepsis" },
        {
          title: "TORCH",
          items: [
            "Sífilis",
            "VIH",
            "Hepatitis",
            "CMV",
            "Rubéola",
            "Toxoplasmosis",
            "HSV",
            "Listeria",
          ],
        },
      ],
    },
    {
      key: "respiratorio",
      title: "C. Respiratorio neonatal",
      topics: [
        { title: "EMH" },
        { title: "Taquipnea transitoria" },
        { title: "SAM" },
        { title: "Hipertensión pulmonar" },
        { title: "Displasia broncopulmonar" },
        { title: "Neumotórax" },
        { title: "Oxigenoterapia" },
        { title: "Ventilación" },
        { title: "CPAP" },
      ],
    },
    {
      key: "cardiologia",
      title: "D. Cardiología neonatal",
      topics: [
        { title: "CIA" },
        { title: "CIV" },
        { title: "PCA" },
        { title: "Tetralogía de Fallot" },
        { title: "Transposición de grandes vasos" },
        { title: "Coartación aórtica" },
        { title: "Cardiopatías dependientes de ductus" },
      ],
    },
    {
      key: "gastro",
      title: "E. Gastroenterología neonatal",
      topics: [
        { title: "Atresias" },
        { title: "Estenosis" },
        { title: "Enterocolitis necrotizante" },
        { title: "Malrotación" },
        { title: "Gastrosquisis" },
        { title: "Onfalocele" },
      ],
    },
    {
      key: "neuro",
      title: "F. Neurología neonatal",
      topics: [
        { title: "Convulsiones neonatales" },
        { title: "HIE" },
        { title: "Hemorragia intraventricular" },
        { title: "Leucomalacia periventricular" },
      ],
    },
    {
      key: "endocrino",
      title: "G. Endocrino neonatal",
      topics: [
        { title: "Hipotiroidismo congénito" },
        { title: "Hiperplasia suprarrenal congénita" },
        { title: "Errores innatos del metabolismo" },
        { title: "Tamiz neonatal" },
      ],
    },
    {
      key: "nutricion",
      title: "H. Nutrición neonatal",
      topics: [
        { title: "Lactancia materna" },
        { title: "Nutrición enteral" },
        { title: "Nutrición parenteral" },
        { title: "Fortificadores" },
        { title: "Prematuros" },
      ],
    },
  ],
};

export const PEDIATRIA: BlueprintBlock = {
  key: "pediatria",
  title: "Pediatría",
  tagline: "26 áreas académicas — del lactante al adolescente.",
  accent: "oklch(0.62 0.11 185)",
  categories: [
    {
      key: "crecimiento",
      title: "2. Crecimiento y desarrollo",
      topics: [
        { title: "Antropometría" },
        { title: "OMS" },
        { title: "Percentiles" },
        { title: "Z score" },
        { title: "Velocidad de crecimiento" },
        { title: "Pubertad" },
        { title: "Tanner" },
        { title: "Desarrollo psicomotor" },
        { title: "Denver" },
        { title: "TEA" },
        { title: "TDAH" },
        { title: "Retraso del desarrollo" },
        { title: "Macrocefalia" },
        { title: "Microcefalia" },
        { title: "Talla baja" },
        { title: "Obesidad" },
      ],
    },
    {
      key: "nutricion-ped",
      title: "3. Nutrición pediátrica",
      topics: [
        { title: "Lactancia materna" },
        { title: "Alimentación complementaria" },
        { title: "BLW" },
        { title: "Desnutrición" },
        { title: "Obesidad" },
        { title: "Micronutrientes" },
        { title: "Vitamina D" },
        { title: "Hierro" },
        { title: "Zinc" },
        { title: "Raquitismo" },
        { title: "Escorbuto" },
      ],
    },
    {
      key: "vacunas",
      title: "4. Vacunas",
      topics: [
        { title: "Calendario Perú" },
        { title: "Calendario CDC" },
        { title: "Calendario AAP" },
        { title: "Calendario Brasil" },
        {
          title: "Esquemas especiales",
          items: ["Prematuros", "VIH", "Inmunodeficiencias", "Trasplante", "Oncología"],
        },
        { title: "Errores frecuentes" },
        { title: "Eventos adversos" },
        { title: "Catch-up" },
        { title: "Casos clínicos" },
      ],
    },
    {
      key: "infectologia",
      title: "5. Infectología",
      topics: [
        { title: "Fiebre" },
        { title: "Sepsis" },
        { title: "ITU" },
        { title: "Neumonía" },
        { title: "Meningitis" },
        { title: "Dengue" },
        { title: "Malaria" },
        { title: "Tuberculosis" },
        { title: "VIH" },
        { title: "COVID" },
        { title: "Influenza" },
        { title: "Varicela" },
        { title: "Sarampión" },
        { title: "Escarlatina" },
        { title: "Exantemas" },
        { title: "Parásitos" },
        { title: "Micosis" },
        { title: "Zoonosis" },
        { title: "Infecciones congénitas" },
        { title: "Antibióticos" },
        { title: "Antivirales" },
      ],
    },
    {
      key: "neumo",
      title: "6. Neumología",
      topics: [
        { title: "Asma" },
        { title: "Bronquiolitis" },
        { title: "Neumonía" },
        { title: "Fibrosis quística" },
        { title: "Tos crónica" },
        { title: "Cuerpo extraño" },
        { title: "Apnea" },
        { title: "Oxigenoterapia" },
        { title: "VNI" },
        { title: "Ventilación mecánica" },
      ],
    },
    {
      key: "cardio",
      title: "7. Cardiología",
      topics: [
        { title: "Cardiopatías congénitas" },
        { title: "Soplos" },
        { title: "Insuficiencia cardíaca" },
        { title: "Shock" },
        { title: "Arritmias" },
        { title: "Kawasaki" },
        { title: "Miocarditis" },
        { title: "Hipertensión" },
        { title: "ECG pediátrico" },
      ],
    },
    {
      key: "gastro-ped",
      title: "8. Gastroenterología",
      topics: [
        { title: "RGE" },
        { title: "Diarrea" },
        { title: "Estreñimiento" },
        { title: "Invaginación" },
        { title: "Apendicitis" },
        { title: "Enfermedad celíaca" },
        { title: "EII" },
        { title: "Hepatitis" },
        { title: "Pancreatitis" },
        { title: "Dolor abdominal" },
      ],
    },
    {
      key: "nefro",
      title: "9. Nefrología",
      topics: [
        { title: "ITU" },
        { title: "Síndrome nefrótico" },
        { title: "Síndrome nefrítico" },
        { title: "IRA" },
        { title: "ERC" },
        { title: "Hematuria" },
        { title: "Proteinuria" },
        { title: "Hipertensión" },
        { title: "Malformaciones" },
        { title: "Litiasis" },
      ],
    },
    {
      key: "endo-ped",
      title: "10. Endocrinología",
      topics: [
        { title: "Diabetes" },
        { title: "Hipotiroidismo" },
        { title: "Pubertad precoz" },
        { title: "Pubertad retrasada" },
        { title: "Obesidad" },
        { title: "Hipoglicemia" },
        { title: "Hiperplasia suprarrenal" },
        { title: "Alteraciones del calcio" },
      ],
    },
    {
      key: "hemato",
      title: "11. Hematología",
      topics: [
        { title: "Anemias" },
        { title: "Ferropenia" },
        { title: "Talasemia" },
        { title: "Drepanocitosis" },
        { title: "PTI" },
        { title: "Leucemias" },
        { title: "Hemofilia" },
        { title: "CID" },
        { title: "Púrpuras" },
        { title: "Transfusiones" },
      ],
    },
    {
      key: "onco",
      title: "12. Oncología",
      topics: [
        { title: "LLA" },
        { title: "LMA" },
        { title: "Linfomas" },
        { title: "Tumor de Wilms" },
        { title: "Neuroblastoma" },
        { title: "Retinoblastoma" },
        { title: "Sarcomas" },
        { title: "Tumores SNC" },
      ],
    },
    {
      key: "neuro-ped",
      title: "13. Neurología",
      topics: [
        { title: "Convulsiones" },
        { title: "Epilepsia" },
        { title: "Parálisis cerebral" },
        { title: "Cefalea" },
        { title: "Hipotonía" },
        { title: "Hipertonía" },
        { title: "Meningitis" },
        { title: "TCE" },
        { title: "Coma" },
      ],
    },
    {
      key: "cx",
      title: "14. Cirugía pediátrica",
      topics: [
        { title: "Abdomen agudo" },
        { title: "Apendicitis" },
        { title: "Hernias" },
        { title: "Hipospadias" },
        { title: "Criptorquidia" },
        { title: "Invaginación" },
        { title: "Estenosis pilórica" },
        { title: "Atresias" },
        { title: "Malrotación" },
      ],
    },
    {
      key: "urgencias",
      title: "15. Urgencias pediátricas",
      topics: [
        { title: "ABCDE" },
        { title: "Shock" },
        { title: "Convulsión" },
        { title: "Anafilaxia" },
        { title: "Trauma" },
        { title: "Quemaduras" },
        { title: "Ahogamiento" },
        { title: "Intoxicaciones" },
        { title: "PCR" },
        { title: "RCP" },
      ],
    },
    {
      key: "uci",
      title: "16. Cuidados intensivos pediátricos",
      topics: [
        { title: "Ventilación" },
        { title: "Shock séptico" },
        { title: "Shock cardiogénico" },
        { title: "Shock hipovolémico" },
        { title: "Sedación" },
        { title: "Analgesia" },
        { title: "Inotrópicos" },
        { title: "ECMO" },
        { title: "Balance hídrico" },
        { title: "Gasometría" },
      ],
    },
    {
      key: "adolescencia",
      title: "17. Adolescencia",
      topics: [
        { title: "Pubertad" },
        { title: "Salud mental" },
        { title: "Conductas de riesgo" },
        { title: "Anticoncepción" },
        { title: "ITS" },
        { title: "Trastornos alimentarios" },
      ],
    },
    {
      key: "derma",
      title: "18. Dermatología",
      topics: [
        { title: "Exantemas" },
        { title: "Hemangiomas" },
        { title: "Dermatitis" },
        { title: "Psoriasis" },
        { title: "Escabiosis" },
        { title: "Impétigo" },
        { title: "Acné" },
      ],
    },
    {
      key: "reuma",
      title: "19. Reumatología",
      topics: [
        { title: "AIJ" },
        { title: "LES" },
        { title: "Vasculitis" },
        { title: "Kawasaki" },
        { title: "PFAPA" },
      ],
    },
    {
      key: "genetica",
      title: "20. Genética",
      topics: [
        { title: "Síndrome de Down" },
        { title: "Turner" },
        { title: "Klinefelter" },
        { title: "Noonan" },
        { title: "Marfan" },
        { title: "Williams" },
        { title: "Cri du Chat" },
        { title: "Errores innatos" },
      ],
    },
    {
      key: "metabolismo",
      title: "21. Metabolismo",
      topics: [
        { title: "Errores innatos" },
        { title: "Acidosis" },
        { title: "Hiperamonemia" },
        { title: "PKU" },
        { title: "Galactosemia" },
        { title: "MSUD" },
      ],
    },
    {
      key: "toxicologia",
      title: "22. Toxicología",
      topics: [
        { title: "Intoxicaciones" },
        { title: "Mordeduras" },
        { title: "Picaduras" },
        { title: "Plantas" },
        { title: "Medicamentos" },
      ],
    },
    {
      key: "ambulatoria",
      title: "23. Pediatría ambulatoria",
      topics: [
        { title: "Control del niño sano" },
        { title: "CRED" },
        { title: "Consejería" },
        { title: "Tamizajes" },
        { title: "Prevención" },
      ],
    },
    {
      key: "mbe",
      title: "24. Pediatría basada en la evidencia",
      topics: [
        { title: "Guías AAP" },
        { title: "NICE" },
        { title: "ESPGHAN" },
        { title: "ESPID" },
        { title: "IDSA" },
        { title: "WHO" },
        { title: "MINSA" },
        { title: "EsSalud" },
      ],
    },
    {
      key: "examen-fisico",
      title: "25. Examen físico pediátrico",
      topics: [
        { title: "Por sistemas" },
        { title: "Hallazgos normales" },
        { title: "Hallazgos patológicos" },
        { title: "Videos" },
        { title: "OSCE" },
      ],
    },
    {
      key: "farmacologia",
      title: "26. Farmacología pediátrica",
      topics: [
        { title: "Calculadora de dosis por peso y superficie corporal" },
        { title: "Diluciones" },
        { title: "Compatibilidad de medicamentos" },
        { title: "Velocidades de infusión" },
        { title: "Antibióticos" },
        { title: "Anticonvulsivantes" },
        { title: "Sedantes" },
        { title: "Inotrópicos" },
        { title: "Analgésicos" },
        { title: "Antipiréticos" },
        { title: "Antialérgicos" },
        { title: "Broncodilatadores" },
        { title: "Corticoides" },
        { title: "Electrolitos" },
        { title: "Nutrición parenteral" },
      ],
    },
  ],
};

export const PEDIATRIA_NEONATOLOGIA_BLUEPRINT: BlueprintBlock[] = [NEONATOLOGIA, PEDIATRIA];
