/**
 * Atlas anatómico de KotaMed Anatomy Lab.
 *
 * Fuente de datos desacoplada del motor 3D: cada estructura declara su
 * sistema, región y su ficha académica completa (anatomía, histología,
 * embriología, fisiología, clínica, imagenología y preguntas de examen).
 * Añadir nuevas estructuras aquí no requiere tocar el visor.
 */

export type SystemKey =
  | "esqueleto"
  | "muscular"
  | "nervioso"
  | "arterial"
  | "venoso"
  | "linfatico"
  | "organos"
  | "fascias"
  | "piel";

export type RegionKey =
  | "cabeza"
  | "cuello"
  | "torax"
  | "abdomen"
  | "pelvis"
  | "miembro-superior"
  | "miembro-inferior"
  | "cuerpo-completo";

export type ViewMode =
  | "anatomia"
  | "histologia"
  | "embriologia"
  | "fisiologia"
  | "imagenologia"
  | "cirugia"
  | "traumatologia"
  | "pediatria"
  | "radiologia"
  | "examen";

export interface AnatomyStructure {
  id: string;
  name: string;
  latin: string;
  terminologia: string;
  system: SystemKey;
  region: RegionKey;
  description: string;
  origen?: string;
  insercion?: string;
  inervacion?: string;
  irrigacion?: string;
  funcion: string;
  embriologia: string;
  histologia: string;
  fisiologia: string;
  patologias: string[];
  imagenologia: string[];
  clinica: string;
  procedimientos: string[];
  preguntas: { enam: string; residentado: string; essalud: string };
  bibliografia: string[];
  dificultad: 1 | 2 | 3 | 4 | 5;
  minutos: number;
  relacionadas: string[];
  /** Cursos de Ciencias Básicas donde la estructura es transversal. */
  cursos: string[];
}

export const SYSTEMS: { key: SystemKey; label: string; color: string; defaultOn: boolean }[] = [
  { key: "esqueleto", label: "Esquelético", color: "#e6ddc9", defaultOn: true },
  { key: "muscular", label: "Muscular", color: "#b0463f", defaultOn: true },
  { key: "nervioso", label: "Nervioso", color: "#f2d861", defaultOn: true },
  { key: "arterial", label: "Arterial", color: "#c8392f", defaultOn: true },
  { key: "venoso", label: "Venoso", color: "#3f6fb5", defaultOn: true },
  { key: "linfatico", label: "Linfático", color: "#79c9a8", defaultOn: false },
  { key: "organos", label: "Órganos", color: "#a44a5c", defaultOn: true },
  { key: "fascias", label: "Fascias", color: "#d9cbb2", defaultOn: false },
  { key: "piel", label: "Piel", color: "#d8a17a", defaultOn: false },
];

export const REGIONS: { key: RegionKey; label: string }[] = [
  { key: "cuerpo-completo", label: "Cuerpo completo" },
  { key: "cabeza", label: "Cabeza y encéfalo" },
  { key: "cuello", label: "Cuello" },
  { key: "torax", label: "Tórax" },
  { key: "abdomen", label: "Abdomen" },
  { key: "pelvis", label: "Pelvis" },
  { key: "miembro-superior", label: "Miembro superior" },
  { key: "miembro-inferior", label: "Miembro inferior" },
];

export const VIEW_MODES: { key: ViewMode; label: string; hint: string; systems: SystemKey[] }[] = [
  { key: "anatomia", label: "Anatomía", hint: "Vista macroscópica estándar", systems: ["esqueleto", "muscular", "organos", "nervioso", "arterial", "venoso"] },
  { key: "histologia", label: "Histología", hint: "Correlación tisular de la estructura", systems: ["organos"] },
  { key: "embriologia", label: "Embriología", hint: "Origen y desarrollo", systems: ["organos", "nervioso"] },
  { key: "fisiologia", label: "Fisiología", hint: "Función dinámica y animaciones", systems: ["organos", "arterial", "venoso"] },
  { key: "imagenologia", label: "Imagenología", hint: "Correlación con cortes y radiología", systems: ["esqueleto", "organos"] },
  { key: "cirugia", label: "Cirugía", hint: "Planos y reparos quirúrgicos", systems: ["muscular", "organos", "arterial", "fascias"] },
  { key: "traumatologia", label: "Traumatología", hint: "Hueso, articulación y ligamento", systems: ["esqueleto", "muscular"] },
  { key: "pediatria", label: "Pediatría", hint: "Particularidades del paciente pediátrico", systems: ["esqueleto", "organos"] },
  { key: "radiologia", label: "Radiología", hint: "Modo rayos X translúcido", systems: ["esqueleto", "organos"] },
  { key: "examen", label: "Examen", hint: "Etiquetas ocultas: identifica la estructura", systems: ["esqueleto", "muscular", "organos", "nervioso"] },
];

export const IMAGING_MODALITIES = [
  "Radiografía",
  "Tomografía",
  "Resonancia",
  "Ecografía",
  "Reconstrucción 3D",
  "Corte axial",
  "Corte sagital",
  "Corte coronal",
] as const;

const B = {
  gray: "Gray. Anatomía para estudiantes, 4.ª ed.",
  moore: "Moore. Anatomía con orientación clínica, 9.ª ed.",
  netter: "Netter. Atlas de anatomía humana, 8.ª ed.",
  guyton: "Guyton & Hall. Tratado de fisiología médica, 14.ª ed.",
  ross: "Ross. Histología texto y atlas, 8.ª ed.",
  langman: "Langman. Embriología médica, 15.ª ed.",
  robbins: "Robbins. Patología estructural y funcional, 10.ª ed.",
};

export const ATLAS: AnatomyStructure[] = [
  {
    id: "corazon",
    name: "Corazón",
    latin: "Cor",
    terminologia: "Cor (TA: A12.1.00.001)",
    system: "organos",
    region: "torax",
    description:
      "Órgano muscular hueco situado en el mediastino medio que actúa como bomba para impulsar la sangre a través del sistema circulatorio.",
    inervacion: "Plexo cardíaco (simpático T1-T5 y parasimpático vagal)",
    irrigacion: "Arterias coronarias derecha e izquierda",
    funcion: "Bombear sangre hacia la circulación pulmonar y sistémica manteniendo el gasto cardíaco.",
    embriologia: "Deriva del tubo cardíaco primitivo del mesodermo esplácnico; plegamiento y tabicación entre la 4.ª y 8.ª semana.",
    histologia: "Endocardio, miocardio (cardiomiocitos con discos intercalares) y epicardio; sistema de conducción con células de Purkinje.",
    fisiologia: "Ciclo cardíaco con sístole y diástole; precarga, poscarga y contractilidad determinan el volumen sistólico.",
    patologias: ["Infarto agudo de miocardio", "Insuficiencia cardíaca", "Valvulopatías", "Miocardiopatías", "Endocarditis infecciosa"],
    imagenologia: ["Silueta cardíaca en radiografía PA", "Ecocardiograma transtorácico", "AngioTAC coronario", "RM cardíaca con realce tardío"],
    clinica: "El dolor torácico opresivo irradiado a brazo izquierdo orienta a isquemia miocárdica; correlacionar con ECG y troponinas.",
    procedimientos: ["Pericardiocentesis", "Cateterismo cardíaco", "Angioplastia coronaria", "Cirugía de revascularización"],
    preguntas: {
      enam: "Varón de 58 años con dolor precordial de 40 min y elevación del ST en cara inferior. ¿Qué arteria está comprometida con mayor frecuencia?",
      residentado: "Explique la fisiopatología de la insuficiencia cardíaca con fracción de eyección preservada y su manejo inicial.",
      essalud: "Paciente con soplo holosistólico en foco mitral irradiado a axila. Diagnóstico más probable y estudio confirmatorio.",
    },
    bibliografia: [B.moore, B.guyton, B.robbins],
    dificultad: 4,
    minutos: 45,
    relacionadas: ["aorta", "pulmones", "vena-cava"],
    cursos: ["Anatomía", "Fisiología", "Histología", "Embriología", "Patología", "Farmacología"],
  },
  {
    id: "encefalo",
    name: "Encéfalo",
    latin: "Encephalon",
    terminologia: "Encephalon (TA: A14.1.03.001)",
    system: "nervioso",
    region: "cabeza",
    description: "Porción del sistema nervioso central alojada en la cavidad craneal: cerebro, cerebelo y tronco encefálico.",
    inervacion: "Doce pares craneales; control autonómico central",
    irrigacion: "Polígono de Willis (carótidas internas y sistema vertebrobasilar)",
    funcion: "Integrar información sensitiva, generar respuestas motoras y sostener funciones superiores.",
    embriologia: "Tubo neural → prosencéfalo, mesencéfalo y rombencéfalo; cierre del neuroporo anterior al día 25.",
    histologia: "Corteza de seis capas, neuronas piramidales, astrocitos, oligodendrocitos y microglía; barrera hematoencefálica.",
    fisiologia: "Potenciales de acción, neurotransmisión sináptica, autorregulación del flujo sanguíneo cerebral.",
    patologias: ["ACV isquémico", "Hemorragia intracerebral", "Epilepsia", "Tumores del SNC", "Meningitis"],
    imagenologia: ["TAC cerebral sin contraste", "RM con difusión", "AngioRM del polígono de Willis"],
    clinica: "Déficit neurológico focal de inicio súbito obliga a descartar ACV dentro de la ventana terapéutica.",
    procedimientos: ["Punción lumbar", "Craniectomía descompresiva", "Trombectomía mecánica"],
    preguntas: {
      enam: "Paciente con hemiparesia derecha y afasia de Broca. ¿Qué territorio arterial está comprometido?",
      residentado: "Criterios de trombólisis endovenosa en ACV isquémico agudo y contraindicaciones absolutas.",
      essalud: "Diferencie clínicamente hemorragia subaracnoidea de cefalea tensional.",
    },
    bibliografia: [B.netter, B.guyton, B.langman],
    dificultad: 5,
    minutos: 60,
    relacionadas: ["medula-espinal", "craneo"],
    cursos: ["Anatomía", "Fisiología", "Histología", "Embriología", "Patología"],
  },
  {
    id: "pulmones",
    name: "Pulmones",
    latin: "Pulmones",
    terminologia: "Pulmo dexter et sinister (TA: A06.5.01.001)",
    system: "organos",
    region: "torax",
    description: "Órganos respiratorios pares alojados en las cavidades pleurales, con tres lóbulos a la derecha y dos a la izquierda.",
    irrigacion: "Arterias bronquiales (nutricia) y arterias pulmonares (funcional)",
    inervacion: "Plexo pulmonar (vago y simpático torácico)",
    funcion: "Realizar el intercambio gaseoso alvéolo-capilar.",
    embriologia: "Divertículo respiratorio del intestino anterior (4.ª semana); fases pseudoglandular, canalicular, sacular y alveolar.",
    histologia: "Epitelio respiratorio ciliado, neumocitos tipo I y II productores de surfactante, macrófagos alveolares.",
    fisiologia: "Ventilación/perfusión, distensibilidad, curva de disociación de la hemoglobina.",
    patologias: ["Neumonía", "EPOC", "Asma", "TEP", "Cáncer de pulmón"],
    imagenologia: ["Radiografía de tórax PA y lateral", "TAC de alta resolución", "AngioTAC pulmonar", "Ecografía pulmonar (líneas B)"],
    clinica: "La disnea con hipoxemia refractaria y radiografía limpia sugiere tromboembolismo pulmonar.",
    procedimientos: ["Toracocentesis", "Broncoscopía", "Drenaje torácico", "Biopsia transbronquial"],
    preguntas: {
      enam: "Niño de 3 años con fiebre, taquipnea y crepitantes focales. Conducta inicial según MINSA.",
      residentado: "Interprete una gasometría con acidosis respiratoria crónica compensada.",
      essalud: "Indicaciones de tubo de drenaje torácico en neumotórax espontáneo.",
    },
    bibliografia: [B.moore, B.guyton, B.ross],
    dificultad: 3,
    minutos: 40,
    relacionadas: ["corazon", "diafragma", "costillas"],
    cursos: ["Anatomía", "Fisiología", "Histología", "Embriología", "Microbiología"],
  },
  {
    id: "higado",
    name: "Hígado",
    latin: "Hepar",
    terminologia: "Hepar (TA: A05.8.01.001)",
    system: "organos",
    region: "abdomen",
    description: "Glándula más voluminosa del organismo, situada en el hipocondrio derecho bajo la cúpula diafragmática.",
    irrigacion: "Arteria hepática propia (25%) y vena porta (75%)",
    inervacion: "Plexo hepático (celíaco y vago)",
    funcion: "Metabolismo intermediario, detoxificación, síntesis proteica y producción de bilis.",
    embriologia: "Divertículo hepático del endodermo del intestino anterior (3.ª-4.ª semana).",
    histologia: "Lobulillos hexagonales, hepatocitos en cordones, sinusoides, células de Kupffer y espacio porta.",
    fisiologia: "Ciclo de la urea, gluconeogénesis, metabolismo de fármacos por citocromo P450.",
    patologias: ["Hepatitis viral", "Cirrosis", "Hígado graso", "Hepatocarcinoma", "Colestasis"],
    imagenologia: ["Ecografía abdominal", "TAC trifásica", "Elastografía hepática", "Colangio-RM"],
    clinica: "Ictericia con hipertransaminasemia obliga a diferenciar patrón hepatocelular de colestásico.",
    procedimientos: ["Biopsia hepática", "Paracentesis", "TIPS", "Trasplante hepático"],
    preguntas: {
      enam: "Paciente alcohólico con ascitis y circulación colateral. ¿Qué complicación explica la hemorragia digestiva alta?",
      residentado: "Clasificación de Child-Pugh y su utilidad pronóstica.",
      essalud: "Interpretación de un perfil hepático colestásico con FA y GGT elevadas.",
    },
    bibliografia: [B.moore, B.ross, B.robbins],
    dificultad: 4,
    minutos: 40,
    relacionadas: ["estomago", "intestino"],
    cursos: ["Anatomía", "Fisiología", "Histología", "Bioquímica", "Patología", "Farmacología"],
  },
  {
    id: "rinones",
    name: "Riñones",
    latin: "Renes",
    terminologia: "Ren (TA: A08.1.01.001)",
    system: "organos",
    region: "abdomen",
    description: "Órganos retroperitoneales pares situados entre T12 y L3, responsables de la filtración glomerular.",
    irrigacion: "Arterias renales, ramas directas de la aorta abdominal",
    inervacion: "Plexo renal (simpático T10-L1)",
    funcion: "Regular el volumen, la osmolaridad y el equilibrio ácido-base; producir eritropoyetina y renina.",
    embriologia: "Pronefros → mesonefros → metanefros; ascenso renal entre la 6.ª y 9.ª semana.",
    histologia: "Nefrona: corpúsculo renal, túbulo contorneado proximal, asa de Henle, túbulo distal y colector.",
    fisiologia: "Filtración, reabsorción y secreción tubular; eje renina-angiotensina-aldosterona.",
    patologias: ["Enfermedad renal crónica", "Lesión renal aguda", "Glomerulonefritis", "Litiasis renal", "Pielonefritis"],
    imagenologia: ["Ecografía renal y vesical", "UroTAC", "Renograma isotópico"],
    clinica: "La oliguria con elevación de creatinina requiere clasificar la lesión en prerrenal, renal o posrenal.",
    procedimientos: ["Biopsia renal", "Nefrostomía percutánea", "Hemodiálisis", "Litotricia"],
    preguntas: {
      enam: "Paciente con cólico lumbar irradiado a genitales y hematuria. Estudio inicial de elección.",
      residentado: "Estadificación KDIGO de la enfermedad renal crónica.",
      essalud: "Criterios de inicio de terapia de reemplazo renal de urgencia.",
    },
    bibliografia: [B.moore, B.guyton, B.ross],
    dificultad: 4,
    minutos: 35,
    relacionadas: ["aorta", "columna"],
    cursos: ["Anatomía", "Fisiología", "Histología", "Bioquímica", "Patología"],
  },
  {
    id: "estomago",
    name: "Estómago",
    latin: "Gaster",
    terminologia: "Gaster (TA: A05.5.01.001)",
    system: "organos",
    region: "abdomen",
    description: "Dilatación del tubo digestivo entre el esófago y el duodeno, con cardias, fundus, cuerpo, antro y píloro.",
    irrigacion: "Arterias gástricas derecha e izquierda, gastroomentales y gástricas cortas",
    inervacion: "Troncos vagales anterior y posterior; simpático del plexo celíaco",
    funcion: "Almacenar el bolo alimentario, iniciar la digestión proteica y regular el vaciamiento gástrico.",
    embriologia: "Dilatación del intestino anterior con rotación de 90° sobre su eje longitudinal.",
    histologia: "Mucosa con foveolas, células parietales (HCl y factor intrínseco), principales (pepsinógeno) y G (gastrina).",
    fisiologia: "Fases cefálica, gástrica e intestinal de la secreción ácida; bomba H+/K+ ATPasa.",
    patologias: ["Enfermedad ulcerosa péptica", "Gastritis por H. pylori", "ERGE", "Adenocarcinoma gástrico"],
    imagenologia: ["Endoscopía alta", "Serie esófago-gastro-duodenal", "TAC con contraste oral"],
    clinica: "El dolor epigástrico que mejora con la ingesta orienta a úlcera duodenal.",
    procedimientos: ["Endoscopía diagnóstica y terapéutica", "Gastrostomía", "Gastrectomía"],
    preguntas: {
      enam: "Esquema de erradicación de Helicobacter pylori de primera línea.",
      residentado: "Diagnóstico diferencial del dolor epigástrico agudo en el servicio de emergencia.",
      essalud: "Signos de alarma que obligan a endoscopía en dispepsia.",
    },
    bibliografia: [B.moore, B.ross, B.guyton],
    dificultad: 3,
    minutos: 30,
    relacionadas: ["higado", "intestino"],
    cursos: ["Anatomía", "Fisiología", "Histología", "Microbiología", "Farmacología"],
  },
  {
    id: "intestino",
    name: "Intestino delgado y grueso",
    latin: "Intestinum tenue et crassum",
    terminologia: "Intestinum (TA: A05.6.01.001)",
    system: "organos",
    region: "abdomen",
    description: "Segmento digestivo desde el duodeno hasta el recto, principal sitio de absorción de nutrientes.",
    irrigacion: "Arterias mesentéricas superior e inferior",
    inervacion: "Sistema nervioso entérico (plexos de Meissner y Auerbach)",
    funcion: "Digestión terminal, absorción de nutrientes, agua y electrolitos.",
    embriologia: "Asa intestinal primitiva con herniación fisiológica y rotación de 270° antihoraria.",
    histologia: "Vellosidades y microvellosidades, criptas de Lieberkühn, células caliciformes y de Paneth, placas de Peyer.",
    fisiologia: "Peristaltismo, absorción por transportadores SGLT1 y circulación enterohepática.",
    patologias: ["Enfermedad celíaca", "Enfermedad inflamatoria intestinal", "Apendicitis", "Obstrucción intestinal", "Cáncer colorrectal"],
    imagenologia: ["Radiografía de abdomen de pie", "TAC abdominal con contraste", "Colonoscopía", "Enterografía por RM"],
    clinica: "Dolor migratorio a fosa ilíaca derecha con Blumberg positivo orienta a apendicitis aguda.",
    procedimientos: ["Apendicectomía", "Colonoscopía", "Colostomía", "Resección intestinal"],
    preguntas: {
      enam: "Escala de Alvarado en el diagnóstico de apendicitis aguda.",
      residentado: "Manejo escalonado de la obstrucción intestinal por bridas.",
      essalud: "Tamizaje de cáncer colorrectal: método y edad de inicio.",
    },
    bibliografia: [B.moore, B.ross, B.robbins],
    dificultad: 3,
    minutos: 35,
    relacionadas: ["estomago", "higado"],
    cursos: ["Anatomía", "Fisiología", "Histología", "Patología", "Parasitología"],
  },
  {
    id: "craneo",
    name: "Cráneo",
    latin: "Cranium",
    terminologia: "Cranium (TA: A02.1.00.001)",
    system: "esqueleto",
    region: "cabeza",
    description: "Conjunto óseo que protege el encéfalo y conforma el macizo facial; neurocráneo y viscerocráneo.",
    irrigacion: "Arterias meníngeas y ramas de la carótida externa",
    inervacion: "Ramas del trigémino para el periostio y la duramadre",
    funcion: "Proteger el encéfalo y sostener los órganos de los sentidos.",
    embriologia: "Osificación intramembranosa (bóveda) y endocondral (base); fontanelas cerradas hacia los 18 meses.",
    histologia: "Hueso compacto con tablas externa e interna separadas por diploe esponjoso.",
    fisiologia: "Cavidad inextensible: doctrina de Monro-Kellie para la presión intracraneal.",
    patologias: ["Fractura de base de cráneo", "Hematoma epidural", "Craneosinostosis"],
    imagenologia: ["TAC de cráneo en ventana ósea", "Radiografía de cráneo", "Reconstrucción 3D"],
    clinica: "El hematoma epidural clásico se asocia a fractura temporal con lesión de la meníngea media.",
    procedimientos: ["Trepanación", "Craneotomía", "Monitoreo de PIC"],
    preguntas: {
      enam: "Intervalo lúcido tras TEC: diagnóstico más probable.",
      residentado: "Indicaciones de TAC en TEC leve según criterios canadienses.",
      essalud: "Signos clínicos de fractura de base de cráneo.",
    },
    bibliografia: [B.netter, B.moore],
    dificultad: 3,
    minutos: 30,
    relacionadas: ["encefalo", "columna"],
    cursos: ["Anatomía", "Embriología", "Patología"],
  },
  {
    id: "columna",
    name: "Columna vertebral",
    latin: "Columna vertebralis",
    terminologia: "Columna vertebralis (TA: A02.2.00.001)",
    system: "esqueleto",
    region: "cuerpo-completo",
    description: "Eje óseo formado por 33 vértebras con curvaturas cervical, torácica, lumbar y sacra.",
    irrigacion: "Arterias segmentarias y arteria espinal anterior",
    inervacion: "Ramos meníngeos recurrentes de los nervios espinales",
    funcion: "Soporte axial, protección medular y movilidad del tronco.",
    embriologia: "Esclerotomo somítico con resegmentación; núcleo pulposo derivado de la notocorda.",
    histologia: "Hueso trabecular, disco intervertebral con anillo fibroso y núcleo pulposo.",
    fisiologia: "Distribución de cargas axiales y amortiguación discal.",
    patologias: ["Hernia discal", "Espondilolistesis", "Estenosis del canal", "Fracturas vertebrales"],
    imagenologia: ["Radiografía dinámica", "RM de columna", "TAC con reconstrucción sagital"],
    clinica: "La lumbociática con Lasègue positivo sugiere compromiso radicular L5-S1.",
    procedimientos: ["Punción lumbar", "Bloqueo epidural", "Discectomía", "Artrodesis"],
    preguntas: {
      enam: "Nivel habitual de punción lumbar en el adulto y su justificación anatómica.",
      residentado: "Banderas rojas del dolor lumbar agudo.",
      essalud: "Diferencie claudicación neurógena de vascular.",
    },
    bibliografia: [B.moore, B.netter, B.langman],
    dificultad: 4,
    minutos: 40,
    relacionadas: ["medula-espinal", "pelvis"],
    cursos: ["Anatomía", "Embriología", "Patología"],
  },
  {
    id: "costillas",
    name: "Caja torácica",
    latin: "Cavea thoracis",
    terminologia: "Costae et sternum (TA: A02.3.02.001)",
    system: "esqueleto",
    region: "torax",
    description: "Estructura osteocartilaginosa formada por 12 pares costales, esternón y vértebras torácicas.",
    irrigacion: "Arterias intercostales posteriores y anteriores",
    inervacion: "Nervios intercostales (T1-T11)",
    funcion: "Proteger los órganos torácicos y permitir la mecánica ventilatoria.",
    embriologia: "Derivada del esclerotomo y del mesodermo somático de la pared corporal.",
    histologia: "Hueso compacto con médula hematopoyética activa en el esternón.",
    fisiologia: "Movimientos en asa de balde y brazo de bomba durante la inspiración.",
    patologias: ["Fracturas costales", "Tórax inestable", "Costocondritis"],
    imagenologia: ["Radiografía de parrilla costal", "TAC de tórax", "Ecografía costal"],
    clinica: "El paquete vasculonervioso corre por el borde inferior de la costilla: puncionar por el borde superior de la costilla inferior.",
    procedimientos: ["Toracocentesis", "Bloqueo intercostal", "Punción esternal"],
    preguntas: {
      enam: "Sitio correcto de inserción del tubo torácico y su justificación anatómica.",
      residentado: "Manejo del tórax inestable con contusión pulmonar.",
      essalud: "Complicaciones de fracturas costales múltiples en el adulto mayor.",
    },
    bibliografia: [B.moore, B.netter],
    dificultad: 2,
    minutos: 25,
    relacionadas: ["pulmones", "diafragma"],
    cursos: ["Anatomía", "Fisiología"],
  },
  {
    id: "pelvis",
    name: "Pelvis ósea",
    latin: "Pelvis",
    terminologia: "Pelvis (TA: A02.5.02.001)",
    system: "esqueleto",
    region: "pelvis",
    description: "Anillo óseo formado por los dos coxales, el sacro y el cóccix; contiene las vísceras pélvicas.",
    irrigacion: "Arterias ilíacas internas",
    inervacion: "Plexo sacro y plexo hipogástrico inferior",
    funcion: "Transmitir el peso axial a los miembros inferiores y contener el canal del parto.",
    embriologia: "Osificación endocondral con cartílago trirradiado que se fusiona en la adolescencia.",
    histologia: "Hueso esponjoso con médula ósea roja; sínfisis púbica fibrocartilaginosa.",
    fisiologia: "Diámetros pélvicos y su relevancia en el mecanismo del parto.",
    patologias: ["Fractura de pelvis", "Desproporción cefalopélvica", "Disfunción del piso pélvico"],
    imagenologia: ["Radiografía de pelvis AP", "TAC pélvica", "Pelvimetría por RM"],
    clinica: "La fractura de pelvis inestable puede provocar shock hipovolémico por sangrado retroperitoneal.",
    procedimientos: ["Fijación externa pélvica", "Cesárea", "Punción suprapúbica"],
    preguntas: {
      enam: "Diámetro pélvico más importante en el estrecho superior.",
      residentado: "Clasificación de Young-Burgess de las fracturas pélvicas.",
      essalud: "Manejo inicial del shock en fractura pélvica inestable.",
    },
    bibliografia: [B.moore, B.netter],
    dificultad: 3,
    minutos: 30,
    relacionadas: ["columna", "femur"],
    cursos: ["Anatomía", "Embriología"],
  },
  {
    id: "femur",
    name: "Fémur",
    latin: "Os femoris",
    terminologia: "Femur (TA: A02.5.04.001)",
    system: "esqueleto",
    region: "miembro-inferior",
    description: "Hueso largo del muslo, el más voluminoso del esqueleto humano.",
    irrigacion: "Arteria circunfleja femoral medial (cabeza femoral) y arteria nutricia",
    inervacion: "Ramos del femoral, obturador y ciático para el periostio",
    funcion: "Transmitir el peso corporal y servir de palanca para la marcha.",
    embriologia: "Osificación endocondral desde el centro diafisario en la 7.ª semana.",
    histologia: "Osteonas de hueso compacto en la diáfisis, hueso trabecular en las epífisis.",
    fisiologia: "Remodelación ósea permanente según la ley de Wolff.",
    patologias: ["Fractura de cadera", "Necrosis avascular de la cabeza femoral", "Osteosarcoma"],
    imagenologia: ["Radiografía de cadera AP y axial", "RM para necrosis avascular", "TAC preoperatoria"],
    clinica: "La fractura de cuello femoral en el anciano se presenta con acortamiento y rotación externa.",
    procedimientos: ["Osteosíntesis con clavo cefalomedular", "Artroplastia de cadera", "Punción intraósea"],
    preguntas: {
      enam: "Signo clínico clásico de la fractura de cuello femoral.",
      residentado: "Clasificación de Garden y su implicancia terapéutica.",
      essalud: "Profilaxis tromboembólica tras artroplastia de cadera.",
    },
    bibliografia: [B.moore, B.netter, B.robbins],
    dificultad: 2,
    minutos: 25,
    relacionadas: ["pelvis", "cuadriceps"],
    cursos: ["Anatomía", "Patología"],
  },
  {
    id: "humero",
    name: "Húmero",
    latin: "Humerus",
    terminologia: "Humerus (TA: A02.4.04.001)",
    system: "esqueleto",
    region: "miembro-superior",
    description: "Hueso largo del brazo articulado con la escápula y con el cúbito y radio.",
    irrigacion: "Arteria braquial profunda y circunflejas humerales",
    inervacion: "Nervio radial en el surco espiral; axilar en el cuello quirúrgico",
    funcion: "Palanca del miembro superior para la prensión y elevación.",
    embriologia: "Osificación endocondral; núcleos epifisarios proximales entre los 6 meses y 5 años.",
    histologia: "Compacta diafisaria con canal medular amplio.",
    fisiologia: "Distribución de fuerzas en la articulación glenohumeral.",
    patologias: ["Fractura de cuello quirúrgico", "Fractura diafisaria con lesión radial", "Luxación glenohumeral"],
    imagenologia: ["Radiografía de hombro AP y axilar", "TAC 3D", "RM del manguito rotador"],
    clinica: "La fractura de la diáfisis humeral puede producir mano caída por lesión del nervio radial.",
    procedimientos: ["Reducción cerrada", "Osteosíntesis con placa", "Bloqueo interescalénico"],
    preguntas: {
      enam: "Nervio lesionado con mayor frecuencia en fractura del cuello quirúrgico del húmero.",
      residentado: "Manejo de la fractura humeral diafisaria con parálisis radial primaria.",
      essalud: "Maniobras de reducción de luxación glenohumeral anterior.",
    },
    bibliografia: [B.moore, B.netter],
    dificultad: 2,
    minutos: 20,
    relacionadas: ["biceps"],
    cursos: ["Anatomía"],
  },
  {
    id: "aorta",
    name: "Aorta",
    latin: "Aorta",
    terminologia: "Aorta (TA: A12.2.02.001)",
    system: "arterial",
    region: "cuerpo-completo",
    description: "Arteria de mayor calibre del organismo: porciones ascendente, cayado, torácica descendente y abdominal.",
    irrigacion: "Vasa vasorum",
    inervacion: "Plexo aórtico; barorreceptores del cayado (nervio vago)",
    funcion: "Distribuir la sangre oxigenada desde el ventrículo izquierdo a todo el organismo.",
    embriologia: "Deriva de los arcos aórticos IV y VI y de la aorta dorsal.",
    histologia: "Arteria elástica: túnica media con láminas de elastina fenestradas.",
    fisiologia: "Efecto Windkessel que mantiene el flujo diastólico continuo.",
    patologias: ["Aneurisma de aorta abdominal", "Disección aórtica", "Coartación aórtica", "Ateroesclerosis"],
    imagenologia: ["AngioTAC de aorta", "Ecografía abdominal para AAA", "AngioRM"],
    clinica: "El dolor torácico transfixiante con asimetría de pulsos obliga a descartar disección aórtica.",
    procedimientos: ["Reparación endovascular (EVAR/TEVAR)", "Cirugía abierta de aneurisma"],
    preguntas: {
      enam: "Indicación de reparación electiva de un aneurisma de aorta abdominal por diámetro.",
      residentado: "Clasificación de Stanford y manejo inicial de la disección aórtica.",
      essalud: "Tamizaje ecográfico de aneurisma aórtico: población objetivo.",
    },
    bibliografia: [B.moore, B.guyton, B.robbins],
    dificultad: 4,
    minutos: 35,
    relacionadas: ["corazon", "rinones"],
    cursos: ["Anatomía", "Fisiología", "Histología", "Patología"],
  },
  {
    id: "vena-cava",
    name: "Vena cava",
    latin: "Vena cava superior et inferior",
    terminologia: "Vena cava (TA: A12.3.02.001)",
    system: "venoso",
    region: "cuerpo-completo",
    description: "Troncos venosos que devuelven la sangre desoxigenada de la circulación sistémica a la aurícula derecha.",
    irrigacion: "Vasa vasorum",
    inervacion: "Fibras simpáticas del plexo torácico y abdominal",
    funcion: "Retorno venoso sistémico hacia el corazón derecho.",
    embriologia: "Desarrollo complejo desde las venas cardinales, subcardinales y supracardinales.",
    histologia: "Pared delgada con abundante colágeno y músculo liso longitudinal.",
    fisiologia: "Capacitancia venosa y determinantes de la precarga; onda de pulso yugular.",
    patologias: ["Síndrome de vena cava superior", "Trombosis venosa profunda", "Insuficiencia venosa"],
    imagenologia: ["AngioTAC venoso", "Ecodoppler venoso", "Flebografía"],
    clinica: "Edema en esclavina con ingurgitación yugular sugiere síndrome de vena cava superior.",
    procedimientos: ["Cateterismo venoso central", "Filtro de vena cava inferior"],
    preguntas: {
      enam: "Causa más frecuente de síndrome de vena cava superior en el adulto.",
      residentado: "Indicaciones actuales del filtro de vena cava inferior.",
      essalud: "Puntos de referencia anatómicos para el acceso venoso yugular interno.",
    },
    bibliografia: [B.moore, B.netter],
    dificultad: 3,
    minutos: 25,
    relacionadas: ["corazon"],
    cursos: ["Anatomía", "Fisiología"],
  },
  {
    id: "medula-espinal",
    name: "Médula espinal",
    latin: "Medulla spinalis",
    terminologia: "Medulla spinalis (TA: A14.1.02.001)",
    system: "nervioso",
    region: "cuerpo-completo",
    description: "Porción del SNC contenida en el conducto vertebral, desde el bulbo hasta el cono medular en L1-L2.",
    irrigacion: "Arteria espinal anterior y arterias espinales posteriores",
    inervacion: "31 pares de nervios espinales",
    funcion: "Conducir vías ascendentes y descendentes e integrar reflejos medulares.",
    embriologia: "Tubo neural; ascenso relativo del cono medular por crecimiento diferencial.",
    histologia: "Sustancia gris en H con astas anterior, lateral y posterior; sustancia blanca en cordones.",
    fisiologia: "Arco reflejo monosináptico, vía piramidal y vía espinotalámica.",
    patologias: ["Sección medular", "Síndrome de Brown-Séquard", "Mielitis transversa", "Siringomielia"],
    imagenologia: ["RM de médula espinal", "TAC mielografía"],
    clinica: "La disociación termoalgésica contralateral con déficit motor ipsilateral define el Brown-Séquard.",
    procedimientos: ["Punción lumbar", "Anestesia raquídea", "Descompresión medular"],
    preguntas: {
      enam: "Nivel del cono medular en el adulto.",
      residentado: "Escala ASIA en la valoración de la lesión medular aguda.",
      essalud: "Diferencias clínicas entre lesión de motoneurona superior e inferior.",
    },
    bibliografia: [B.netter, B.guyton, B.langman],
    dificultad: 5,
    minutos: 50,
    relacionadas: ["encefalo", "columna"],
    cursos: ["Anatomía", "Fisiología", "Histología", "Embriología"],
  },
  {
    id: "diafragma",
    name: "Diafragma",
    latin: "Diaphragma",
    terminologia: "Diaphragma (TA: A04.4.02.001)",
    system: "muscular",
    region: "torax",
    description: "Músculo musculotendinoso que separa las cavidades torácica y abdominal.",
    origen: "Porciones esternal, costal y lumbar (pilares en L1-L3)",
    insercion: "Centro tendinoso",
    inervacion: "Nervio frénico (C3-C4-C5)",
    irrigacion: "Arterias frénicas inferiores y musculofrénicas",
    funcion: "Principal músculo de la inspiración.",
    embriologia: "Septum transversum, membranas pleuroperitoneales, mesenterio esofágico y pared corporal.",
    histologia: "Músculo estriado esquelético con predominio de fibras tipo I resistentes a la fatiga.",
    fisiologia: "Su contracción reduce la presión intrapleural y genera el flujo inspiratorio.",
    patologias: ["Hernia diafragmática congénita", "Parálisis frénica", "Hernia hiatal"],
    imagenologia: ["Radiografía de tórax", "Ecografía diafragmática", "Fluoroscopía dinámica"],
    clinica: "C3, C4 y C5 mantienen el diafragma vivo: lesiones cervicales altas requieren ventilación mecánica.",
    procedimientos: ["Plicatura diafragmática", "Reparación de hernia de Bochdalek"],
    preguntas: {
      enam: "Raíces del nervio frénico y consecuencia de su lesión.",
      residentado: "Manejo neonatal de la hernia diafragmática congénita.",
      essalud: "Orificios diafragmáticos y sus estructuras a nivel T8, T10 y T12.",
    },
    bibliografia: [B.moore, B.guyton, B.langman],
    dificultad: 3,
    minutos: 30,
    relacionadas: ["pulmones", "costillas"],
    cursos: ["Anatomía", "Fisiología", "Embriología"],
  },
  {
    id: "biceps",
    name: "Bíceps braquial",
    latin: "Musculus biceps brachii",
    terminologia: "M. biceps brachii (TA: A04.6.02.013)",
    system: "muscular",
    region: "miembro-superior",
    description: "Músculo bicipital de la región anterior del brazo con cabeza larga y cabeza corta.",
    origen: "Tubérculo supraglenoideo (cabeza larga) y apófisis coracoides (cabeza corta)",
    insercion: "Tuberosidad del radio y aponeurosis bicipital",
    inervacion: "Nervio musculocutáneo (C5-C6)",
    irrigacion: "Arteria braquial",
    funcion: "Flexión del codo y supinación del antebrazo.",
    embriologia: "Mioblastos del dermomiotomo de los somitas cervicales bajos.",
    histologia: "Fibras estriadas con sarcómeros, husos neuromusculares y unión miotendinosa.",
    fisiologia: "Acoplamiento excitación-contracción mediado por calcio y puentes de actina-miosina.",
    patologias: ["Rotura del tendón de la cabeza larga", "Tendinitis bicipital"],
    imagenologia: ["Ecografía musculotendinosa", "RM de hombro y codo"],
    clinica: "El signo de Popeye indica rotura de la cabeza larga del bíceps.",
    procedimientos: ["Tenodesis bicipital", "Infiltración ecoguiada"],
    preguntas: {
      enam: "Raíz evaluada por el reflejo bicipital.",
      residentado: "Diagnóstico diferencial del dolor anterior de hombro.",
      essalud: "Prueba de Yergason: técnica e interpretación.",
    },
    bibliografia: [B.moore, B.netter, B.ross],
    dificultad: 2,
    minutos: 20,
    relacionadas: ["humero"],
    cursos: ["Anatomía", "Fisiología", "Histología"],
  },
  {
    id: "cuadriceps",
    name: "Cuádriceps femoral",
    latin: "Musculus quadriceps femoris",
    terminologia: "M. quadriceps femoris (TA: A04.7.02.017)",
    system: "muscular",
    region: "miembro-inferior",
    description: "Grupo muscular anterior del muslo con recto femoral y tres vastos.",
    origen: "Espina ilíaca anteroinferior y línea áspera del fémur",
    insercion: "Tuberosidad tibial a través del tendón rotuliano",
    inervacion: "Nervio femoral (L2-L4)",
    irrigacion: "Arteria femoral profunda",
    funcion: "Extensión de la rodilla y estabilización de la marcha.",
    embriologia: "Miotomos lumbares con migración ventral del brote del miembro.",
    histologia: "Fibras tipo I y II con proporción variable según entrenamiento.",
    fisiologia: "Reflejo patelar monosináptico L4; generación de torque extensor.",
    patologias: ["Rotura del tendón cuadricipital", "Atrofia por desuso", "Síndrome femoropatelar"],
    imagenologia: ["Ecografía muscular", "RM de rodilla"],
    clinica: "La abolición del reflejo patelar orienta a radiculopatía L4 o neuropatía femoral.",
    procedimientos: ["Inyección intramuscular en vasto lateral", "Reparación tendinosa"],
    preguntas: {
      enam: "Sitio seguro para inyección intramuscular en el muslo del lactante.",
      residentado: "Rehabilitación tras reconstrucción del ligamento cruzado anterior.",
      essalud: "Nivel radicular evaluado por el reflejo rotuliano.",
    },
    bibliografia: [B.moore, B.netter],
    dificultad: 2,
    minutos: 20,
    relacionadas: ["femur", "pelvis"],
    cursos: ["Anatomía", "Fisiología"],
  },
];

export const ATLAS_BY_ID: Record<string, AnatomyStructure> = Object.fromEntries(
  ATLAS.map((s) => [s.id, s]),
);

/** Mapea el nombre de un curso/lección a la región que debe cargar el visor. */
export function regionForLesson(text: string): { region: RegionKey; focus?: string } {
  const t = (text ?? "").toLowerCase();
  const rules: { match: string[]; region: RegionKey; focus?: string }[] = [
    { match: ["corazón", "corazon", "cardio", "cardiac"], region: "torax", focus: "corazon" },
    { match: ["pulmon", "respirat", "vía aérea"], region: "torax", focus: "pulmones" },
    { match: ["nervioso", "encéfalo", "encefalo", "cerebro", "neuro"], region: "cabeza", focus: "encefalo" },
    { match: ["médula", "medula", "raquídea"], region: "cuerpo-completo", focus: "medula-espinal" },
    { match: ["pelvis", "obstetric", "ginecolog"], region: "pelvis", focus: "pelvis" },
    { match: ["miembro superior", "brazo", "hombro", "codo"], region: "miembro-superior", focus: "humero" },
    { match: ["miembro inferior", "pierna", "rodilla", "cadera", "muslo"], region: "miembro-inferior", focus: "femur" },
    { match: ["hígado", "higado", "hepat"], region: "abdomen", focus: "higado" },
    { match: ["riñón", "rinon", "renal", "nefro"], region: "abdomen", focus: "rinones" },
    { match: ["digestiv", "estómago", "estomago", "intestin", "gastro"], region: "abdomen", focus: "estomago" },
    { match: ["abdomen"], region: "abdomen" },
    { match: ["tórax", "torax"], region: "torax" },
    { match: ["cabeza", "cráneo", "craneo"], region: "cabeza", focus: "craneo" },
  ];
  for (const r of rules) if (r.match.some((m) => t.includes(m))) return { region: r.region, focus: r.focus };
  return { region: "cuerpo-completo" };
}
